### ISSUE TITLE
Duplicate requirements are not detected / warned / disallowed

### ISSUE THREAD

**Issue by mlawren** [miyagawa/cpanfile#36]
By mistake I "require"d the same module twice, but with different versions:

    on "runtime" => sub {
        require 'Time::Piece';
        # ...
        require 'Time::Piece' => '1.30';
    }

To prevent unintended behaviour (in this case the second require is ignored) multiple definitions within an "on" block should at least be "warn"d, if not disallowed altogether.

**Comment by miyagawa** [comment]
right now the second one overrides the first one, and I think it's not the right behavior.

It needs to merge multiple occurrences of the same module, so that:

```
requires 'Time::Piece', '1';
requires 'Time::Piece', '!= 1.1';
```

will be merged to `1, != 1.1`.

If you have these multiple requirements in *different* phases, i.e. `test` and `runtime` you'll get a merged result via CPAN::Meta::Requirements already.
