### ISSUE TITLE
Ability to say "I always want the latest version of this dependency"

### ISSUE THREAD

**Issue by DrHyde** [miyagawa/cpanfile#40]
`requires 'Some::Module'` will install the latest version if Some::Module isn't already installed, but if it is installed it will leave it alone.

Sometimes it's Really Handy to just have the latest version all the time - quite a lot of modules come with embedded data, such as ParseUtil::Domain (which is what prompted this feature request) or my own Number::Phone, and being able to say something like `requires 'Some::Module', 'latest'` would enable me to force developer machines to stay up to date.

**Comment by miyagawa** [comment]
Personally I don't think that's a useful feature, but if it is for some occasions, I'd recommend some other mechanism to enforce that. cpanfile version requirement is aiming at a compatibility to CPAN::Meta spec, with a sugar to specify some mirror functionality.

**Comment by worthmine** [comment]
I've read the PODs and searched 'How can I always require the latest within cpanfile?' and finally reached here.

Do you mean there is no way to do that?

I think it's convenient if `requires 'Some::Module', undef;`(with no omission) means requesting the latest.
Because I wrote like `requires 'Module::CoreList', '5.20200920';` in [my module](https://github.com/worthmine/App-findeps) and I felt that is not sophisticated. 

Certainly, I can run `cpanm Module::CoreList` to refresh it before running my script but I think it's not TIMTOWTDI.

**Comment by miyagawa** [comment]
"the latest version" varies from time to time, depending on what the CPAN (PAUSE) server has on its own index. The whole purpose of `cpanfile` and its snapshot mechanism is to describe a consistent and reliable view of what versions of modules you need.

**Comment by worthmine** [comment]
Fine. I thought you'll say so😁
